config/routes.rb
Rails.application.routes.draw do
resources :books
root 'books#home'

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :reviews  
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :books 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def home
  end


  def index
    @books = Book.all
  end


  def show
   @book = Book.find(params[:id])
   @reviews = @book.reviews
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<h1>Bookmarks</h1>
<ol>

  <% @books.each do |book| %>
    <li class="book">
      <div class="row">
        <div class="col col-xs-1">
          <p class="rank-this-week"> <%=book.rank_this_week%> </p>
        </div>
        <div class="col col-xs-9">
          <h3 class="title"><%= book.title%> </h3>
          <p class="author">by <%=book.author%>  </p>
          <p class="publisher">(<%=book.publisher%>)</p>
          <p class="description"> <%=book.description%> </p>
          <p class="all-reviews"> <a href="/books/show" </a> <%=link_to 'See all Editorial Reviews', book_path(book)%></p>
        </div>
        <div class="col col-xs-2">
          <p class="weeks-on-list"><%=book.weeks_on_list%> weeks on list</p>
        </div>
      </div>
    </li>
  <%end%>
</ol>

app/views/books/show.html.erb
<div class="header">
  <h1>Bookmarks</h1>
</div>
<div class="book">
  <p class="title"><%= @book.title %></p>
  <p class="author">by <%= @book.author %></p>
  <p class="publisher">(<%= @book.publisher %>)</p>
  <p class="description"><%= @book.description %></p>
</div>
<div class="reviews">
    <% @reviews.each do |review| %>
     <div class="review">
      <p class="author"><%= review.author %></p>
      <p class="comment"><%= review.comment %></p>
     </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmarks</title>
  <link href="/app/assets/images/literature_filled_50_yXe_icon.ico" rel="shortcut icon" type="image/icon" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container"

      <%= yield %>

  </div>
</body>
</html>